# Generated by Django 3.1.1 on 2020-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recieve',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='send',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='recieve',
            name='message',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='send',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
