# Generated by Django 3.1.1 on 2020-11-21 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201121_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 56, 43, 263342)),
        ),
        migrations.AddField(
            model_name='recieve',
            name='get_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='message',
            field=models.TextField(),
        ),
    ]
